class Mask():
    def __init__(self, originalMask, scaledMask, duplicate):
        # The original mask, as generated by Mask R-CNN
        self.originalMask = originalMask

        # The mask scaled to the resolution of the bounding box
        self.scaledMask = scaledMask

        # Is this the original mask entity generated during detection, or is it a duplicate?
        # If this is the original, then the scaled mask fits perfectly with the original bounding box.
        # If this is the duplicate, then the scaled mask may be slightly distorted to fit the
        #   new bounding box captured during tracking.
        self.duplicate = duplicate

    def getOriginalMask(self):
        return self.originalMask

    def getScaledMask(self):
        return self.scaledMask

    def isDuplicate(self):
        return self.duplicate